name: Test SDK
on:
  - push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: xcodebuild test -scheme FoxentrySdk -destination 'platform=iOS Simulator'
